SELECT A, COUNT (DISINCT B) 
FROM table GROUP BY A 
HAVING COUNT (DISTINCT B) > 1;

CREATE TRIGGER trigger
BEFORE INTERT OR UPDATE ON table
FOR EACH ROW
WHEN (OLD.A != NEW.A)
BEGIN
    IF (NEW.A = OLD.A AND NEW.B != OLD.B)
    THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Violation of A -> B';
    END IF;
END;

SELECT A, COUNT (DISTINCT B)
FROM table 
WHERE A IS NOT NULL AND B IS NOT NULL
GROUP BY A
HAVING COUNT (DISTINCT B) > 1;

CREATE TRIGGER trigger
BEFORE INTERT OR UPDATE ON table
FOR EACH ROW
WHEN (OLD.A != NEW.A)
BEGIN
    IF (NEW.A = OLD.A AND NEW.B IS NULL OR OLD.B IS NULL OR NEW.B != OLD.B) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Violation of A -> B';
    END IF;
END;